DEVELOPMENT = True

# SERVER
DEBUG = True
SECRET_KEY = ""
HOST_ADDRESS = "http://localhost:5000"
GOOGLE_API_KEY = ""
DATABASE = "sqlite:///data/dev.db"
SMTP_SETTINGS = {
    "MAIL_SERVER": "",
    "MAIL_PORT": 0,
    "MAIL_USE_SSL": True,
    "MAIL_USERNAME": "",
    "MAIL_PASSWORD": "",
    "DEFAULT_MAIL_SENDER": ("", "")
}

# REAL WORLD CONSTANTS
EARTH_RADIUS = 6371000

# APPLICATION
NUMBER_OF_HOTELS_RETURNED = 5
NUMBER_OF_RESTAURANTS_RETURNED = 5
HOTEL_THRESHOLDS = { 1: 75,
                     2: 100,
                     3: 250,
                     4: 375,
                     5: 99999 }
DEFAULT_MAX_TRAVEL_DURATION = 36000
DEFAULT_CORRIDOR_DURATION = 1800
COUNTRIES_TO_LOAD = ['US']
HOTEL_COVERAGE_LAT = 0.1
HOTEL_COVERAGE_LNG = 0.15
DEFAULT_EARLY_WEIGHT = 1
DEFAULT_DETOUR_WEIGHT = 100000

if not DEVELOPMENT:
    from production import *
